repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.6.0"
    hooks:
      - id: trailing-whitespace
        exclude_types: [svg]
      - id: end-of-file-fixer
      - id: check-yaml
